### ISSUE TITLE
RealMines load error

### ISSUE THREAD

**Issue by DarkBladeDev** [joserodpt/RealMines#41]
[11:17:01] [Server thread/ERROR]: Error occurred while enabling RealMines v1.6.1 (Is it up to date?)
java.lang.IllegalArgumentException: name cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.getWorld(CraftServer.java:1443) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at org.bukkit.Bukkit.getWorld(Bukkit.java:844) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at joserodpt.realmines.manager.MineManager.loadMines(MineManager.java:225) ~[RealMines-1.6.1.jar:?]
	at joserodpt.realmines.RealMines.onEnable(RealMines.java:181) ~[RealMines-1.6.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2092]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[11:17:01] [Server thread/INFO]: [RealMines] Disabling RealMines v1.6.1

My server is running with Purpur 1.20.2

**Comment by joserodpt** [comment]
Hi there! It appears that you have a mine in a world that has not been loaded / doesn't exist

**Comment by joserodpt** [comment]
No further comment from reporter.
