### ISSUE TITLE
Plugin wont work for me

### ISSUE THREAD

**Issue by SkeloD** [joserodpt/RealMines#44]
[04:15:35 INFO]: SkeloD issued server command: /mine mines
[04:15:35 WARN]: java.lang.reflect.InvocationTargetException
[04:15:35 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:15:35 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[04:15:35 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:15:35 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[04:15:35 WARN]: 	at RealMines-1.6.1.jar//josegamerpt.realmines.mf.base.CommandHandler.executeCommand(CommandHandler.java:232)
[04:15:35 WARN]: 	at RealMines-1.6.1.jar//josegamerpt.realmines.mf.base.CommandHandler.execute(CommandHandler.java:218)
[04:15:35 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[04:15:35 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
[04:15:35 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[04:15:35 WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[04:15:35 WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
[04:15:35 WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
[04:15:35 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2354)
[04:15:35 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2314)
[04:15:35 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[04:15:35 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[04:15:35 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:15:35 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[04:15:35 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[04:15:35 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[04:15:35 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[04:15:35 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[04:15:35 WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[04:15:35 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[04:15:35 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
[04:15:35 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[04:15:35 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[04:15:35 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[04:15:35 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:15:35 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[04:15:35 WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[04:15:35 WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[04:15:35 WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[04:15:35 WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[04:15:35 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195)
[04:15:35 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[04:15:35 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[04:15:35 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[04:15:35 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[04:15:35 WARN]: 	at RealMines-1.6.1.jar//joserodpt.realmines.gui.MineListGUI.load(MineListGUI.java:69)
[04:15:35 WARN]: 	at RealMines-1.6.1.jar//joserodpt.realmines.gui.MineListGUI.<init>(MineListGUI.java:63)
[04:15:35 WARN]: 	at RealMines-1.6.1.jar//joserodpt.realmines.command.MineCMD.minescmd(MineCMD.java:78)
[04:15:35 WARN]: 	... 29 more

I might not respond on github so just contact me on discord 
my discord is SkeloD

**Comment by SkeloD** [comment]
one thing i forgot to say its that when i want to change the percentage of a block in the mine menu it wont let me it will just say pls typing a percentage higher than 0 but i did so idk what is happening
[mines.txt](https://github.com/joserodpt/RealMines/files/13831406/mines.txt)
idk if this help but here is the file for my mines

**Comment by joserodpt** [comment]
<img width="532" alt="image" src="https://github.com/joserodpt/RealMines/assets/18755024/f0662426-502f-4dcb-a34c-bea7cc1244ee">
This indicates that the plugin was improperly loaded. Fully restart the server, update the plugin and do it properly.

**Comment by SkeloD** [comment]
i updated and restart fully the server i deleted the file and added them back and nothing work
