### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Clexus** [joserodpt/RealMines#53]
```[16:54:24 WARN]: [RealMines] Task #16706 for RealMines v1.7.4 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
        at java.lang.String.replace(String.java:3086) ~[?:?]
        at joserodpt.realmines.api.config.TranslatableLine.get(TranslatableLine.java:171) ~[RealMines.jar:?]
        at joserodpt.realmines.plugin.gui.GUIManager$3.run(GUIManager.java:219) ~[RealMines.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

```Mines:
  Reset:
    Starting: '&f%mine% &f正在&e重置.'
    Percentage: '&6警告 &f该矿区即将重置.'
    Announcement: '&f矿区 &9%mine% &f重置完毕.'
    Warning: '&7[&6警告&7] &r%mine% &f将在 &b%time% &9秒后重置.'
  Teleport: '&f已传送至 &9%mine%'
  Teleport-Set: '&f已为矿区 %mine% 设置传送点'
  No-Teleport-Location: '&c该矿区没有传送点.'
  Break-Actions:
    Give-Money: '&f你因为破坏该方块获得了&b%money%元&f!'
    Drop-Item: '&f你破坏方块时掉落了一个物品!'
    Give-Item: '&f你破坏方块时背包中被添加了一个物品!'
    Input:
      Command: '在聊天栏输入破坏方块后执行的命令:'
      Amount: '在聊天栏输入给予物品的数量:'
      Amount-Error: '&c你输入的不是有效数字.'
      Chance: '在聊天栏输入执行几率 (0-100%):'
GUI:
  Reset-Name: '&r重置 %mine%'
  Faces-Name: '&r朝向'
  Choose-Name: '&r为 %mine% 选择一种矿区种类:'
  Select-Icon-Name: '&r为 %mine% 选择一个图标'
  Pick-New-Block-Name: '&r选择一个新的方块'
  Mine-Blocks-Name: '%mine% &r包含的方块'
  Color-Picker-Name: '&r选一个颜色'
  Faces:
    Name: '&3&l%face%'
    Selected-Description:
    - '&7已选择方块: &f%material%'
    - '&7按下 &f丢弃键 &c删除.'
    None-Description:
    - '&7已选择方块: &f无'
    - '&7按下 &f丢弃键 &c删除.'
  Resets:
    Percentage-On:
      Name: '&9按几率重置矿区 &7(&a&l开&r&7)'
      Description:
      - '&7左键点击&c关闭'
      - '&f右键输入新的几率.'
      - '&f当前值: &b%value%%'
    Percentage-Off:
      Name: '&9按几率重置矿区 &7(&c&l关&r&7)'
      Description:
      - '&7左键点击&a打开'
      - '&f右键输入新的几率.'
      - '&f当前值: &b%value%%'
    Time-On:
      Name: '&9按时间重置矿区 &7(&a&l开&r&7)'
      Description:
      - '&7左键点击&c关闭'
      - '&f右键输入新的时间.'
      - '&f当前值: &b%value% 秒.'
    Time-Off:
      Name: '&9按时间重置矿区 &7(&c&l关&r&7)'
      Description:
      - '&7左键点击&a打开'
      - '&f右键输入新的时间.'
      - '&f当前值: &b%value% 秒.'
  Items:
    Schematic:
      Name: '&b&l模板'
    Farm:
      Name: '&a&l农场'
    Blocks:
      Name: '&9&l矿区'
      Description:
      - '&f点击打开该分类.'
    Faces:
      Name: '&a&l朝向'
      Description:
      - '&f点击配置矿区朝向.'
    Resets:
      Name: '&6&l重置'
      Description:
      - '&f点击管理重置内容.'
    Teleport:
      Name: '&5&l传送'
      Description:
      - '&f点击传送到该矿区.'
    Icon:
      Name: '&b&l图标'
      Description:
      - '&f点击选择一个新的图标.'
    Name:
      Name: '&f&l名称'
      Description:
      - '&f点击输入一个新名称.'
    Displayname:
      Name: '&a&l展示名'
      Description:
      - '&f点击输入新的展示名.'
    Clear:
      Name: '&c&l清除'
      Description:
      - '&f点击清除该矿区.'
    Reset:
      Name: '&4&l重置'
      Description:
      - '&f点击重置该矿区.'
    Boundaries:
      Name: '&e&l边界'
      Description:
      - '&f点击查看该矿区边界.'
    MineColor:
      Name: '&3&l颜色'
      Description:
      - '&f点击选择该矿区颜色.'
    Add:
      Name: '&b&l添加方块'
      Description:
      - '&f点击添加新的方块.'
      - '&f你也可以点击你背包里的方块把它添加进去!'
    Search:
      Name: '&9&l搜索'
      Description:
      - '&f点击搜索一个方块.'
    Next:
      Name: '&a&l下一页'
      Description:
      - '&f点击前往下一页.'
    Back:
      Name: '&6&l上一页'
      Description:
      - '&f点击前往上一页.'
    Go-Back:
      Name: '&9返回'
      Description:
      - '&7点击返回.'
    Close:
      Name: '&c&l关闭'
      Description:
      - '&f点击关闭该页面.'
    Mine-Block:
      Block:
        Name: '&3&l%material%'
        Description:
        - '&f几率: &b%percentage%%'
        - '&6'
        - '&a&n左键&r&f来编辑几率.'
        - '&e&n右键&r&f来编辑该方块的破坏触发动作.'
        - '&e&nShift+左键&r&f切换该方块是否掉落物品.'
        - '&e&nShift+右键&r&f切换该方块能否被破坏.'
        - '&c&n按丢弃键&r&f将该方块移除.'
      Schematic-Block:
        Name: '&3&l%material%'
        Description:
        - '&6'
        - '&e&n右键&r&f来编辑该方块的破坏触发动作.'
        - '&e&nShift+左键&r&f切换该方块是否掉落物品.'
        - '&e&nShift+右键&r&f切换该方块能否被破坏.'
    Farm-Item:
      Name: '&3&l%material% &r&7- &f年龄(成熟度): &3%age%'
      Description:
      - '&f几率: &b%percentage%%'
      - '&6'
      - '&a&n左键&r&f来编辑几率.'
      - '&e&n右键&r&f来编辑该物品的破坏触发动作.'
      - '&a&nShift+左键&r&f增加年龄.'
      - '&e&nShift+右键&r&f减少年龄.'
      - '&c&n按丢弃键&r&f删除该方块.'
    No-Blocks:
      Name: '&f&l该矿区没有方块!'
      Description:
      - '&f点击上方图标添加新方块!'
    Mine:
      Description:
      - '&3%remainingblocks%&7/&b%totalblocks% &f个方块'
      - '&f%bar%'
      - '&a&n点击&r&f编辑该矿区.'
      - '&c&n按丢弃键&r&f删除该矿区'
    No-Mines-Found:
      Name: '&9&l未找到矿区'
      Description:
      - '&f使用/rm crate <矿区名> 命令创建新的矿区.'
    Pick:
      Name: '&3&l%material%'
      Description:
      - '&f点击选择.'
    Colors:
      Red: '&c&l红'
      Green: '&2&l绿'
      Blue: '&9&l蓝'
      Brown: '&#694b00&l棕'
      Gray: '&7&l灰'
      White: '&f&l白'
      Orange: '&6&l橙色'
      Yellow: '&e&l黄色'
      Purple: '&5&l紫色'
      Description:
      - '&f点击选择颜色.'
System:
  Player-Only: '&c只有玩家可以运行该命令.'
  Boundaries-Not-Set: '&f你&c还没有&f设置矿区范围.'
  Cant-Add-Item: '&f这个物品&c不能&f被添加到矿区中.'
  Mine-Created: '&f矿区 &b%mine% &a已创建.'
  Reloaded: '&a已重载.'
  Mine-Task-Created: '&f矿区任务 &b%task%&7(延迟&e%delay%&7秒) &f已创建.'
  Mine-Task-Exists: '&c已经有该名称的矿区任务了.'
  Mine-Exists: '&c已经有该名称的矿区了.'
  Mine-Linked: '&f矿区&a已连接!'
  Mine-Unlinked: '&f矿区&a已取消链接!'
  Mine-Deleted: '&f矿区已删除.'
  Mine-Task-Doesnt-Exist: '&c没有对应名称的矿区任务.'
  Mine-Doesnt-Exist: '&c没有对应名称的矿区.'
  Mine-Renamed: '&f矿区已被重命名为&b%name%'
  Mine-Clear: '&f矿区已&a清空.'
  Stopped-Mine-Tasks: '&c已停止&f所有的矿区任务.'
  Started-Mine-Tasks: '&a已启动&f所有的矿区任务.'
  Remove: '&f你移除了&b%object%'
  Region-Updated: '&B边界&a已更新.'
  Add-Blocks: '&f你想把这些方块加到矿区里吗? (输入 yes 或者 no)'
  Block-Count: '&f方块数量: &3%count%'
  Blocks-Added: '&b%count% &f个方块已被&a加入&f矿区.'
  Silent-Off: '&f%mine% &a现在将会发送重置提醒.'
  Silent-On: '&f%mine% &c不再发送重置提醒.'
  Update-Found: '&6&l注意! &fRealMines已有新版本!'
  Input-Cancelled: '&f输入取消.'
  Error-Occurred: '&c出现错误. 请联系作者JoseGamer_PT www.spigotmc.org'
  Error-Permission: '&f你&c没有&f权限运行该命令!'
  Error-Command: '&c你要运行的命令不存在!'
  Error-Usage: '&c命令用法错误!'
  Nothing-Found: '&f无法根据你的关键词搜索到内容.'
  Invalid-Schematic: '&c你选择的模板不存在. 你加了后缀名吗? (比如 .schem)'
  Input-Schematic: '&f输入一个 RealMines/schematics 文件夹中的模板文件名称 (比如: schem1.schem)'
  Input-Parse: '&c输入一个 0 到 100 的值.'
  Input-Limit-Error: '&c输入错误. 输入值必须在1到100之间'
  Input-Percentage-Error: '&c输入一个 0 到 100 的值.'
  Input-Percentage-Error-Greater: '&c输入错误. 请输入一个大于 0 的值.'
  Input-Percentage-Error-Lower: '&c输入错误，请输入一个小于等于 100 的值.'
  Input-Limit-Error-Greater: '&c输入错误，请输入一个大于等于 1 的值'
  Input-Seconds: '&c请输入一个时间，单位为秒.'
  Percentage-Modified: '&f几率已调整为 &b%value%'
  Time-Modified: '&f时间已调整为 &b%value% 秒.'
  No-Converter-Available: '&c该插件没有可用的转换器.'
  Mine-Freeze: '%name% &r&f 冻结: '
  # 标题和副标题
  Type-Input:
  - '&9在聊天栏输入你的输入'
  - '&f输入 &4cancel &f取消'
Signs:
  # Split lines with |
  Setting-Not-Found: '&4设置未找到'
  Mine-Not-Found: '&4矿区未找到'
  Mined-On: '的方块在此已开采:'
  Mined-Blocks-On: '的方块在此矿区可被开采:'
  Blocks-On: '个方块在此矿区可被开采:'
  Left-On: '的方块于此矿区剩余:'
Version: 7
```

**Comment by Clexus** [comment]
> Hi there, please check this .jar file and see if it solved your issue, thanks: [RealMines.jar.zip](https://github.com/joserodpt/RealMines/files/15262713/RealMines.jar.zip)

works now
