### ISSUE TITLE
Error after reload

### ISSUE THREAD

**Issue by KhrysAK47** [joserodpt/RealMines#54]
I have created a Mine, afterwards server was rebooted, and now when clicking it from the gui shows this:

```
[18:43:27 WARN]: [RealMines] Task #5024 for RealMines v1.7.4 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "<parameter2>" is null
        at java.lang.String.replace(Unknown Source) ~[?:?]
        at joserodpt.realmines.api.config.TranslatableLine.get(TranslatableLine.java:171) ~[RealMines.jar:?]
        at joserodpt.realmines.plugin.gui.GUIManager$3.run(GUIManager.java:219) ~[RealMines.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-435]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-435]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by KhrysAK47** [comment]
It worked after waiting a few minutes.
